# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Sujan Thapa - Portfolio
name: Sujan Thapa
email: najussujan@gmail.com.com
description: Sujan's Portfolio
twitter_username: najus
github_username: najus

# Build settings
markdown: kramdown
